yatube/api/urls.py
#  импортируйте в код всё необходимое
from django.urls import include, path
from rest_framework import routers

from .views import PostViewSet

app_name = 'api_posts'

router = routers.DefaultRouter()
router.register('api/v1/posts', PostViewSet)


urlpatterns = [
    path('', include(router.urls)),
]

yatube/posts/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import (CommentCreateView, FollowIndexListView, GroupPostsListView,
                    IndexListView, LikePostView, PostCreateView,
                    PostDetailView, PostEditView, ProfileFollowView,
                    ProfileListView, ProfileUnfollowView, UnlikePost)

app_name = 'posts'

urlpatterns = [
    path('',
         IndexListView.as_view(),
         name='index'),

    path('group/<slug:slug>/',
         GroupPostsListView.as_view(),
         name='group_list'),

    path('profile/<str:username>/',
         ProfileListView.as_view(),
         name='profile'),

    path('create/',
         login_required(PostCreateView.as_view()),
         name='post_create'),

    path('posts/<int:post_id>/',
         PostDetailView.as_view(),
         name='post_detail'),

    path('posts/<int:post_id>/comment/',
         login_required(CommentCreateView.as_view()),
         name='add_comment'),

    path('posts/<int:post_id>/edit/',
         login_required(PostEditView.as_view()),
         name='post_edit'),

    path('follow/',
         login_required(FollowIndexListView.as_view()),
         name='follow_index'),

    path('profile/<str:username>/follow/',
         login_required(ProfileFollowView.as_view()),
         name='profile_follow'),

    path('profile/<str:username>/unfollow/',
         login_required(ProfileUnfollowView.as_view()),
         name='profile_unfollow'),

    path('posts/<int:post_id>/like/',
         login_required(LikePostView.as_view()),
         name='post_like'),

    path('posts/<int:post_id>/unlike/',
         login_required(UnlikePost.as_view()),
         name='post_unlike'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls', namespace='api_posts')),
]

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Текст нового поста'
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        to=Group,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
        on_delete=models.SET_NULL,
        blank=True, null=True,
        related_name='posts'
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        to=Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    def clean(self):
        if self.user == self.author:
            raise ValidationError(
                _('Нельзя делать подписываться на самого себя'))

    class Meta:
        unique_together = ['author']


class Like(models.Model):
    post = models.ForeignKey(to=Post,
                             on_delete=models.CASCADE,
                             related_name='likes')
    user = models.ForeignKey(to=User,
                             on_delete=models.CASCADE,
                             related_name='likes')
    like = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.post.text

yatube/posts/forms.py
from django import forms

from posts.models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, FormView, UpdateView
from django.views.generic.list import ListView, View

from posts.forms import CommentForm
from posts.models import Comment, Follow, Group, Like, Post, User


class IndexListView(ListView):
    """Главная страница с функцией поиска постов по ключевому слову"""
    model = Post
    template_name = 'posts/index.html'
    paginate_by = settings.AMOUNT_POSTS

    def get_queryset(self):
        keyword = self.request.GET.get("q", None)
        if keyword:
            page_obj = Post.objects.select_related('author', 'group').filter(
                text__contains=keyword)
        else:
            page_obj = Post.objects.select_related('author', 'group')
        return page_obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Последние обновления на сайте'
        return context


class GroupPostsListView(ListView):
    """Страница постов привязанная к конкретной группе"""
    model = Post
    template_name = 'posts/group_list.html'
    paginate_by = settings.AMOUNT_POSTS

    def get_queryset(self):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))
        queryset = group.posts.select_related('author')
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['group'] = get_object_or_404(
            Group, slug=self.kwargs.get('slug')
        )
        return context


class ProfileListView(ListView):
    """Карточка профайла автора с возможностью подписаться или отписаться"""
    model = Post
    template_name = 'posts/profile.html'
    paginate_by = settings.AMOUNT_POSTS

    def get_queryset(self):
        author = get_object_or_404(User, username=self.kwargs.get('username'))
        queryset = author.posts.select_related('group')
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = get_object_or_404(
            User, username=self.kwargs.get('username'))
        context['posts'] = self.get_queryset()
        if self.request.user.is_authenticated:
            context['following'] = context['author'].following.select_related(
                'user'
            )
        else:
            context['following'] = False
        return context


class PostDetailView(FormView):
    """Карточка поста с формой комментария и лайками"""
    form_class = CommentForm
    template_name = 'posts/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(
            Post, id=self.kwargs.get('post_id'))
        context['posts'] = context['post'].author.posts.count()
        context['comments'] = context['post'].comments.select_related('author')
        if self.request.user.is_authenticated:
            context['likes'] = context['post'].likes.select_related('user')
            context['like_record'] = Like.objects.filter(
                post_id=self.kwargs.get('post_id'), user=self.request.user)
        return context


class PostCreateView(CreateView):
    """Создание поста"""
    model = Post
    template_name = 'posts/create_post.html'
    fields = ['text', 'group', 'image']

    def get_success_url(self):
        return reverse_lazy('posts:profile', args=[self.object.author])

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostEditView(UpdateView):
    """Редактирование поста"""
    model = Post
    template_name = 'posts/create_post.html'
    fields = ['text', 'group', 'image']
    pk_url_kwarg = 'post_id'

    def dispatch(self, request, *args, **kwargs):
        post = get_object_or_404(Post, id=self.kwargs.get('post_id'))
        if self.request.user != post.author:
            return redirect('posts:post_detail', self.kwargs.get('post_id'))
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('posts:post_detail', args=[self.object.id])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_edit'] = True
        return context


class CommentCreateView(CreateView):
    """Создание комментарий"""
    model = Comment
    fields = ['text']

    def get_success_url(self):
        return reverse_lazy(
            'posts:post_detail', kwargs={'post_id': self.kwargs['post_id']})

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post = get_object_or_404(Post,
                                               id=self.kwargs.get('post_id'))
        return super().form_valid(form)


class FollowIndexListView(ListView):
    """Отображение постов любимых авторов"""
    model = Post
    template_name = 'posts/follow.html'
    paginate_by = settings.AMOUNT_POSTS

    def get_queryset(self):
        future_posts = Post.objects.filter(
            author__following__user=self.request.user)
        return future_posts


class ProfileFollowView(View):
    # Подписаться на автора
    def get(self, request, *args, **kwargs):
        author = get_object_or_404(User, username=self.kwargs.get('username'))
        if request.user != author:
            Follow.objects.get_or_create(user=request.user, author=author)
        return redirect('posts:profile', author.username)


class ProfileUnfollowView(View):
    """Отписка от автора"""

    def get(self, request, *args, **kwargs):
        author = get_object_or_404(User, username=self.kwargs.get('username'))
        unfollowing = Follow.objects.filter(user=request.user, author=author)
        unfollowing.delete()
        return redirect('posts:profile', author.username)


class LikePostView(ListView):
    """Лайк"""

    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post, id=self.kwargs.get('post_id'))
        if self.request.user.is_authenticated:
            Like.objects.get_or_create(post_id=post.id,
                                       user=request.user,
                                       like=1)
        return redirect('posts:post_detail', post.id)


class UnlikePost(ListView):
    """Дизлайк"""

    def get(self, request, *args, **kwargs):
        record_like = Like.objects.filter(
            post_id=self.kwargs.get('post_id'), user=request.user)
        record_like.delete()
        return redirect('posts:post_detail', self.kwargs.get('post_id'))

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать запись
            {% else %}
              Новый пост
            {% endif %}
          </div>
          <div class="card-body">
            {% load user_filters %}
            {% include 'includes/form_validation.html' %}

            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <input type="hidden" name="test" value="">
              {% for field in form %}
                <div class="form-group row my-3 p-3 textarea">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text }}
                    </small>
                  {% endif %}
                </div>
            {% endfor %}

              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Тут выводятся посты любимого автора
{% endblock %}

{% block content %}
  <div class="container py-5">
    <h1>Тут выводятся посты любимого автора</h1>
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      {% include 'posts/includes/post_card.html' %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Записи сообщества: {{ group.title }}
{% endblock %}

{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>
      {{ group.description }}
    </p>
    {% for post in page_obj %}
      {% include 'posts/includes/post_card.html' %}
    {% endfor %}
  {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  {{ title }}
{% endblock %}

{% block content %}
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    <form class="d-flex">
      <input name="q" class="form-control me-2" type="search"
             placeholder="Поиск постов" aria-label="Search"
        {% if keyword %}
         value="{{ keyword }}"
        {% endif %}
      style="width: 300px"
      >
      <button class="btn btn-outline-success" type="submit">Найти</button>
    </form>
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      {% include 'posts/includes/post_card.html' %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{#{% load thumbnail %}#}
{% load user_filters thumbnail static %}

{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if not group and post.group %}
            <li class="list-group-item">
              Группа: {{ post.group }}
              <button type="button" class="btn btn-outline-primary djdt-width-20">
                <a href="{% url 'posts:group_list' post.group.slug %}"
                   style="color: black; text-decoration: none; width: 40px">
                  все записи группы
                </a>
            </button>
            </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ posts }}</span>
          </li>
          <li class="list-group-item">
            <button type="button" class="btn btn-outline-primary djdt-width-20">
              <a href="{% url 'posts:profile' post.author %}"
              style="color: black; text-decoration: none">
              все посты пользователя
              </a>
            </button>
          </li>
          <li class="list-group-item">
            {% if like_record%}
              <a class="btn btn-lg btn-light" href="{% url 'posts:post_unlike' post.id %}">
            {% else %}
              <a class="btn btn-lg btn-light" href="{% url 'posts:post_like' post.id %}">
            {% endif %}
              <i class="bi bi-heart-fill">
                <img src="{% static 'img/fav/heart-fill.svg'%}" alt="heart">
              </i>
              {{ likes.count }}
              </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        {% if user == post.author %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            редактировать запись
          </a>
        {% endif %}
        {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}
                <div class="form-group mb-2">
                  {{ form.text|addclass:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
        {% endif %}

        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
              <p>
                {{ comment.text }}
              </p>
            </div>
          </div>
        {% endfor %}
      </article>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}
  Профайл пользователя {{ author }}
{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="mb-5">
      <h1>Все посты пользователя {{ author.get_full_name }}</h1>
      <h3>Всего постов: {{ posts.count }} </h3>
      {% if author != request.user %}
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
      {% endif %}
    </div>
    {% for post in page_obj %}
      {% include 'posts/includes/post_card.html' %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}